name: Kevin Thompson
url: https://kevinthompson.info
description: Developer; indie game enthusiast; husband; father of two clever little girls and a mischievous toddler.
avatar: /assets/images/logo.png
links:
  - title: Social
    icon: fab fa-social-profile
    url: https://twitter.com/kevinthompson
  - title: Github
    icon: fab fa-github
    url: https://github.com/kevinthompson
  - title: Itch.io
    icon: fab fa-itch-io
    url: https://kevinthompson.itch.io
  - title: Email
    icon: fas fa-envelope
    url: mailto:email@kevinthompson.info
